// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyWise.Data.Context;

#nullable disable

namespace MoneyWise.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoneyWise.Data.Entities.PedidoEntity", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime>("DateOfInclusion")
                        .HasColumnType("datetime2")
                        .HasColumnName("dh_inclusao");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("fk_usuario");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_PEDIDO");
                });

            modelBuilder.Entity("MoneyWise.Data.Entities.UsuarioEntity", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime>("DateOfInclusion")
                        .HasColumnType("datetime2")
                        .HasColumnName("dh_inclusao");

                    b.Property<string>("DsCPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_cpf");

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_email");

                    b.Property<string>("DsNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ds_nome");

                    b.Property<int>("NrIdade")
                        .HasColumnType("int")
                        .HasColumnName("nr_idade");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int")
                        .HasColumnName("fk_pedido");

                    b.HasKey("Id");

                    b.ToTable("TB_USUARIO");
                });

            modelBuilder.Entity("MoneyWise.Data.Entities.PedidoEntity", b =>
                {
                    b.HasOne("MoneyWise.Data.Entities.UsuarioEntity", "usuarioEntity")
                        .WithMany("pedidoEntities")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuarioEntity");
                });

            modelBuilder.Entity("MoneyWise.Data.Entities.UsuarioEntity", b =>
                {
                    b.Navigation("pedidoEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
